[package]
name = "shoey"
version = "0.1.0"
authors = ["Damon Smith <damon.default@gmail.com>"]
edition = "2018"


[dependencies]
relm = "^0.16.0"
relm-derive = "^0.16.0"
rustyline = "5.0.3"

[dependencies.gtk]
version = "0.6"
features = ["v3_16"]